name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Start containers
      run: docker compose -f "./Cleipnir.ResilientFunctions/docker-compose.yml" up -d --build           
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
